-- Auto-generated by scripts/parse_questions.py

INSERT INTO topics (id, slug, name_he, description_he, order_index, icon) VALUES
  (gen_random_uuid(), 'signs', 'תמרורים', 'הכרת תמרורי הדרך ומשמעותם', 1, '/signs/sign-302.png'),
  (gen_random_uuid(), 'traffic-laws', 'חוקי התנועה', 'כללי הנסיעה, קדימויות וחובות הנהג', 2, '/signs/sign-301.png'),
  (gen_random_uuid(), 'safety', 'בטיחות', 'נסיעה בטוחה, חגורות ומרחק בטיחות', 3, '/signs/sign-131.png'),
  (gen_random_uuid(), 'vehicle', 'הכרת הרכב', 'מערכות הרכב, תחזוקה ומכניקה בסיסית', 4, '/signs/sign-110.png')
ON CONFLICT (slug) DO NOTHING;
